{{ edit_comment }}

FROM nginx:mainline-alpine

# Labels
# https://github.com/opencontainers/image-spec/blob/main/annotations.md
LABEL "maintainer"="lotyp <lotyp7@gmail.com>"
LABEL "vendor"="wayofdev"
LABEL "org.opencontainers.image.authors"="lotyp <lotyp7@gmail.com>"
LABEL "org.opencontainers.image.url"="https://hub.docker.com/r/wayofdev/nginx"
LABEL "org.opencontainers.image.documentation"="https://github.com/wayofdev/docker-nginx"
LABEL "org.opencontainers.image.source"="https://github.com/wayofdev/docker-nginx"
LABEL "org.opencontainers.image.vendor"="wayofdev"
LABEL "org.opencontainers.image.licenses"="MIT"
LABEL "org.opencontainers.image.ref.name"="{{ level }}-{{ os_name }}"
LABEL "org.opencontainers.image.title"="nginx-{{ level }}-{{ os_name }}"
LABEL "org.opencontainers.image.description"="nginx-{{ level }}-{{ os_name }}"

ENV LANG="en_US.UTF-8"
ENV LC_ALL="en_US.UTF-8"
ENV LANGUAGE="en_US.UTF-8"

ENV PHP_UPSTREAM_CONTAINER=app
ENV PHP_UPSTREAM_PORT=9000

RUN set -eux; \
    apk -U upgrade -a \
    && adduser -u 82 -D -S -G www-data www-data \
    && mkdir -p /etc/nginx/ssl \
    && mkdir -p /app/public \
    && mkdir -p /var/cache/nginx \
    && cp /usr/share/nginx/html/index.html /app/public/

COPY ./configs/00-set-upstream.sh /docker-entrypoint.d
COPY ./configs/00_upstream.conf /etc/nginx/conf.d/00_upstream.conf
COPY ./configs/default.conf /etc/nginx/conf.d/default.conf
COPY ./configs/nginx.conf /etc/nginx/

# Copy SSL configuration files
COPY ./certs/ /etc/nginx/ssl/
COPY ./certs/dhparam.pem /etc/nginx/ssl/dhparam.pem

RUN set -eux \
    && chown 82:82 /docker-entrypoint.d/00-set-upstream.sh \
    && chmod +x /docker-entrypoint.d/00-set-upstream.sh \
    && chown 82:82 /etc/nginx/conf.d/00_upstream.conf \
    && chown 82:82 -R /var/cache/nginx \
    && touch /var/run/nginx.pid \
    && chown 82:82 /var/run/nginx.pid \
    && chown 82:82 -R /etc/nginx/ssl

{% if 'k8s' == level %}
USER 82
{% endif %}

ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE {{ type.ports.http }} {{ type.ports.https }}

STOPSIGNAL SIGQUIT

CMD ["nginx"]
