---

- name: Generate nginx Dockerfiles
  hosts: all
  gather_facts: false
  tags:
    - template
  tasks:
    - name: Create dist for all supported nginx versions
      ansible.builtin.import_tasks: roles/all/main.yml

...
